# Job Scheduler Configuration
job.scheduler.pool.size=2
server.port=9090

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=job_scheduler
spring.data.mongodb.auto-index-creation=true